test_name: Acceso y Configuración de Servicios Digitales
llm:
  temperature: 0.9
  model: gpt-4o-mini
  format:
    type: text
user:
  language: Spanish
  role: Usuario que necesita ayuda con el acceso a servicios digitales y configuración de cuentas.
  context:
  - 'personality: personalities/impatient-user'
  - Como estudiante de una institución educativa, te enfrentas a la necesidad de acceder a varios servicios digitales para completar tus tareas académicas.
  - En particular, te interesa saber cómo configurar tu cuenta y asegurarte de que puedes acceder a plataformas clave como Moodle y la biblioteca.
  - Además, necesitas instrucciones precisas sobre la configuración de herramientas como la VPN para trabajar de manera remota sin dificultades.
  goals:
  - Solicitar detalles sobre las opciones de configuración de cuentas y servicios integrados dentro de ID-UAM.
  - Pedir instrucciones paso a paso para cambiar la contraseña incluyendo cómo obtener un código de activación.
  - Consultar información sobre la necesidad de una cuenta institucional para acceder a Moodle y los diferentes entornos de Moodle disponibles.
  - Solicitar información sobre cómo acceder a los recursos de la biblioteca y la identificación necesaria para hacerlo.
  - Preguntar sobre las opciones y enlaces para instalar y configurar VPN para acceder remotamente a los servicios universitarios.
chatbot:
  is_starter: false
  fallback: ¿Me puedes repetir la pregunta con otras palabras? o, si lo prefieres, puedes consultar nuestro\ncatálogo de servicios\n.\nRespondo a preguntas dirigidas al\nCentro de Atención a Usuarios del servicio de Tecnologías de la Información.
  output:
  - account_configuration_options:
      type: string
      description: Opciones de configuración de cuentas en ID-UAM
  - password_change_steps:
      type: string
      description: Instrucciones para cambiar la contraseña
  - activation_code_info:
      type: string
      description: Obtención del código de activación para contraseña
  - institutional_account_requirement:
      type: string
      description: Necesidad de cuenta institucional para Moodle
  - moodle_environment_options:
      type: string
      description: Entornos de Moodle disponibles (Grado, Postgrado)
  - library_access_info:
      type: string
      description: Requisitos para acceder a recursos de la biblioteca
  - vpn_setup_options:
      type: string
      description: Enlaces para instalar y configurar VPN
  - installation_guides:
      type: string
      description: Guías de instalación específicas del sistema operativo
  - selected_os:
      type: string
      description: Sistema operativo seleccionado para VPN
  - vpn_installation_steps:
      type: string
      description: Pasos para instalar cliente VPN GlobalProtect
conversation:
  number: 3
  max_cost: 0.5
  goal_style:
    steps: 30
  interaction_style:
  - single question
