test_name: Product Exploration and Ordering
llm:
  temperature: 0.4
  model: gpt-4o-mini
  format:
    type: text
user:
  language: English
  role: A user seeking to explore various product categories and order fresh food or groceries online.
  context:
  - 'personality: personalities/impatient-user'
  - You're planning your weekly grocery shopping and want to ensure you have a variety of fresh food options to choose from.
  - Recently, you've been interested in incorporating more seasonal fruits and convenient meal solutions into your diet.
  - You're hoping to explore online ordering options that make this easier and more efficient.
  goals:
  - Ask the chatbot to list the types of fresh food available at Alcampo.
  - Inquire about the variety of seasonal fruits available for online ordering.
  - Request detailed information on the ready-made meal options available.
  - Ask for step-by-step instructions on how to order a specific product online from Alcampo.
  - Request details about the cuts of Galician beef available for ordering.
chatbot:
  is_starter: false
  fallback: 🤩 ¡Qué ilusión ver tu entusiasmo por aprender! 🧑🏻‍🎓 En Alcampo tenemos una sección de libros muy variada 📚 —seguro que encuentras algo que te encante.
  output:
  - fresh_food_categories:
      type: string
      description: Types of fresh food available
  - seasonal_fruits:
      type: string
      description: List of seasonal fruits available
  - ready_made_meals:
      type: string
      description: Overview of ready-made meal options
  - ordering_instructions:
      type: string
      description: Step-by-step instructions for ordering
  - galician_beef_cuts:
      type: string
      description: Details on cuts of Galician beef available
  - total_items_ordered:
      type: int
      description: Total number of items in the order
  - selected_product_name:
      type: string
      description: Name of the product chosen for order
  - ordering_date:
      type: date
      description: Date of the order placement
  - product_price:
      type: money
      description: Price of the selected product
  - delivery_fee:
      type: money
      description: Cost for delivery of the order
  - preparation_time:
      type: time
      description: Estimated time to prepare the order
  - payment_status:
      type: string
      description: Status of the payment transaction
conversation:
  number: 3
  max_cost: 0.5
  goal_style:
    steps: 30
  interaction_style:
  - single question
